import { ProductionDirection, AspectRatio, ScriptType, AudienceType, UeContentType } from '@/models/enums'
import type { ScriptTemplate, TemplateCategory, GameCategory } from '@/models/types/template'

export const TEMPLATE_CATEGORIES: { id: TemplateCategory; label: string }[] = [
  { id: 'popular', label: '热门' },
  { id: 'voiceover', label: '口播类' },
  { id: 'showcase', label: '展示类' },
  { id: 'story', label: '剧情类' },
  { id: 'ue', label: 'UE创意' },
]

export const GAME_CATEGORY_FILTERS: { id: GameCategory | 'all'; label: string }[] = [
  { id: 'all', label: '全部品类' },
  { id: 'slg', label: 'SLG' },
  { id: 'rpg', label: 'RPG' },
  { id: 'casual', label: '休闲' },
  { id: 'card', label: '卡牌' },
  { id: 'moba', label: 'MOBA' },
  { id: 'acg', label: '二次元' },
  { id: 'shooter', label: '射击' },
  { id: 'sim', label: '模拟经营' },
]

export const SCRIPT_TEMPLATES: ScriptTemplate[] = [
  // ═══════════════════════════════════════
  //  热门 — 各品类最常用的模板
  // ═══════════════════════════════════════
  {
    id: 'popular_slg_vo_15',
    name: 'SLG 竖屏口播',
    description: '最常见的买量格式，真人口播 + 游戏画面穿插',
    category: 'popular',
    gameCategory: 'slg',
    icon: '🔥',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.VoGuide,
      audience: AudienceType.Male2535,
    },
    preview: '「兄弟们，这游戏太上头了！我才玩三天就打到王城了…你看这阵容，满屏金将…」',
    recommendedThemeIds: ['tower', 'rescue'],
  },
  {
    id: 'popular_rpg_char_15',
    name: 'RPG 角色展示',
    description: '用高质量角色画面吸引玩家，展示角色技能和特效',
    category: 'popular',
    gameCategory: 'rpg',
    icon: '⚔️',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.ShowcaseCharacter,
      audience: AudienceType.Male1824,
    },
    preview: '【镜头1】角色全身立绘亮相，光影粒子特效\n【镜头2】释放大招，全屏爆发\n【镜头3】多角色切换展示',
    recommendedThemeIds: ['boss', 'bullet'],
  },
  {
    id: 'popular_casual_hook',
    name: '休闲快节奏钩子',
    description: '5秒极短钩子，抓住注意力后快速展示玩法',
    category: 'popular',
    gameCategory: 'casual',
    icon: '⚡',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 5,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.Hook5s,
      audience: AudienceType.General,
    },
    preview: '「等等！你确定不试试？」→ 满屏合成爆炸 → 下载引导',
    recommendedThemeIds: ['asmr', 'merge'],
  },
  {
    id: 'popular_ue_gameplay',
    name: 'UE 创意玩法',
    description: '虚幻引擎 3D 画面，创意玩法展示，视觉冲击力强',
    category: 'popular',
    gameCategory: 'rpg',
    icon: '🎮',
    config: {
      direction: ProductionDirection.UeGameplay,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.UeGameplayScript,
      ueContentType: UeContentType.Gameplay,
    },
    preview: '【镜头1】第一人称进入副本\n【镜头2】BOSS战实机画面\n【镜头3】掉落史诗装备，属性面板',
  },
  {
    id: 'popular_card_vo_15',
    name: '卡牌口播安利',
    description: '真人出镜推荐卡牌游戏，强调收集和阵容搭配',
    category: 'popular',
    gameCategory: 'card',
    icon: '🃏',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.VoIntro,
      audience: AudienceType.Male2535,
    },
    preview: '「这个卡牌游戏的立绘也太精致了吧！你看这个SSR…抽卡手感绝了…」',
    recommendedSellTags: ['角色收集', '角色'],
  },
  {
    id: 'popular_acg_char_15',
    name: '二次元角色展示',
    description: '动漫风角色展示，Live2D + 技能演出，主打立绘和配音',
    category: 'popular',
    gameCategory: 'acg',
    icon: '🌸',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.ShowcaseCharacter,
      audience: AudienceType.Male1824,
    },
    preview: '【镜头1】新角色Live2D待机动画\n【镜头2】日配CV语音 + 技能特写\n【镜头3】突破觉醒新立绘',
    recommendedThemeIds: ['bullet'],
    recommendedSellTags: ['角色', '角色收集'],
  },

  // ═══════════════════════════════════════
  //  口播类
  // ═══════════════════════════════════════
  {
    id: 'vo_slg_guide_30',
    name: 'SLG 口播攻略 30s',
    description: '深度攻略讲解，阵容推荐 + 实战演示',
    category: 'voiceover',
    gameCategory: 'slg',
    icon: '🎙️',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.VoGuide,
      audience: AudienceType.Male2535,
    },
    preview: '「今天教大家一个无敌阵容！这三个将领搭配在一起…看，直接秒杀对面主力…」',
    recommendedThemeIds: ['tower'],
  },
  {
    id: 'vo_rpg_guide_30',
    name: 'RPG 口播攻略 30s',
    description: '角色培养路线和副本攻略讲解',
    category: 'voiceover',
    gameCategory: 'rpg',
    icon: '📖',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.VoGuide,
      audience: AudienceType.Male2535,
    },
    preview: '「很多新手不知道怎么培养角色，其实只要跟着这个路线…三天就能通关困难副本…」',
    recommendedThemeIds: ['boss'],
  },
  {
    id: 'vo_intro_15',
    name: '口播安利 15s',
    description: '直接安利推荐游戏，强调亮点和福利',
    category: 'voiceover',
    gameCategory: 'rpg',
    icon: '📢',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.VoIntro,
      audience: AudienceType.Male2535,
    },
    preview: '「这款游戏我真的吹爆！画质顶级，剧情感人，关键还不氪…」',
  },
  {
    id: 'vo_benefit_15',
    name: '福利向口播 15s',
    description: '主打福利、活动、礼包，降低用户下载门槛',
    category: 'voiceover',
    icon: '🎁',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.VoBenefit,
      audience: AudienceType.General,
    },
    preview: '「现在下载直接送648！还有限定SSR自选…这福利不领亏大了…」',
    recommendedSellTags: ['福利', '高级许愿'],
  },
  {
    id: 'vo_casual_intro_15',
    name: '休闲游戏安利 15s',
    description: '轻松有趣的安利风格，强调解压和上手简单',
    category: 'voiceover',
    gameCategory: 'casual',
    icon: '😊',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.VoIntro,
      audience: AudienceType.General,
    },
    preview: '「下班了不知道玩啥？推荐这个超解压的小游戏，不用动脑，越玩越上头…」',
  },
  {
    id: 'vo_moba_guide_30',
    name: 'MOBA 攻略口播 30s',
    description: '英雄玩法攻略，连招教学 + 实战演示',
    category: 'voiceover',
    gameCategory: 'moba',
    icon: '🏆',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.VoGuide,
      audience: AudienceType.Male1824,
    },
    preview: '「这个英雄太强了！学会这套连招直接上王者…先手2技能接闪现…」',
  },
  {
    id: 'vo_card_benefit_15',
    name: '卡牌福利口播 15s',
    description: '抽卡福利、保底机制宣传，吸引卡牌玩家',
    category: 'voiceover',
    gameCategory: 'card',
    icon: '🎰',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.VoBenefit,
      audience: AudienceType.Male2535,
    },
    preview: '「新服开了！上来就送100抽，30抽保底SSR…我一波直接满命…」',
    recommendedSellTags: ['福利', '高级许愿'],
  },
  {
    id: 'vo_shooter_guide_15',
    name: '射击游戏安利 15s',
    description: '高燃战斗场面 + 口播推荐，强调手感和画质',
    category: 'voiceover',
    gameCategory: 'shooter',
    icon: '🔫',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.VoIntro,
      audience: AudienceType.Male1824,
    },
    preview: '「这射击手感太丝滑了！后坐力真实，枪枪到肉…画质直接拉满…」',
  },
  {
    id: 'vo_sim_intro_30',
    name: '模拟经营口播 30s',
    description: '展示经营玩法，从零建造到繁华城市的过程',
    category: 'voiceover',
    gameCategory: 'sim',
    icon: '🏗️',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.VoGuide,
      audience: AudienceType.General,
    },
    preview: '「从一块空地开始，我建了一座超级城市！你看这个布局…每天收益百万金币…」',
  },
  {
    id: 'vo_acg_intro_15',
    name: '二次元安利口播 15s',
    description: '主打立绘、CV、剧情，吸引二次元玩家',
    category: 'voiceover',
    gameCategory: 'acg',
    icon: '🎀',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.VoIntro,
      audience: AudienceType.Male1824,
    },
    preview: '「这画风也太好看了吧！全日配CV，剧情居然还能让我哭…二次元玩家必入…」',
  },

  // ═══════════════════════════════════════
  //  展示类
  // ═══════════════════════════════════════
  {
    id: 'show_rpg_char_30',
    name: 'RPG 角色展示 30s',
    description: '长版角色展示，多角色轮播 + 技能特效',
    category: 'showcase',
    gameCategory: 'rpg',
    icon: '🦸',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.ShowcaseCharacter,
      audience: AudienceType.Male1824,
    },
    preview: '【镜头1】主角觉醒变身\n【镜头2】三个角色轮番释放大招\n【镜头3】全队合体终结技',
    recommendedThemeIds: ['bullet', 'boss'],
    recommendedSellTags: ['角色', '角色收集'],
  },
  {
    id: 'show_slg_map_15',
    name: 'SLG 地图展示 15s',
    description: '展示游戏大地图、城池和联盟战争场景',
    category: 'showcase',
    gameCategory: 'slg',
    icon: '🗺️',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Landscape,
      scriptType: ScriptType.ShowcaseMap,
      audience: AudienceType.Male2535,
    },
    preview: '【镜头1】俯瞰大世界地图\n【镜头2】城池攻防战特写\n【镜头3】联盟集结进军',
    recommendedThemeIds: ['dungeon'],
  },
  {
    id: 'show_acg_char_15',
    name: '二次元角色 PV 15s',
    description: '新角色宣传 PV，主打立绘和战斗演出',
    category: 'showcase',
    gameCategory: 'acg',
    icon: '✨',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.ShowcaseCharacter,
      audience: AudienceType.Male1824,
    },
    preview: '【镜头1】角色剪影逐渐显现\n【镜头2】Live2D互动特写\n【镜头3】战斗技能全屏演出',
  },
  {
    id: 'show_moba_hero_15',
    name: 'MOBA 英雄展示 15s',
    description: '新英雄技能展示，连招演示 + 团战高光',
    category: 'showcase',
    gameCategory: 'moba',
    icon: '⚡',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.ShowcaseCharacter,
      audience: AudienceType.Male1824,
    },
    preview: '【镜头1】英雄帅气登场\n【镜头2】1v3极限操作\n【镜头3】五杀团灭对面',
  },
  {
    id: 'show_card_summon_15',
    name: '卡牌抽卡展示 15s',
    description: '抽卡动画 + SSR角色展示，制造稀有感',
    category: 'showcase',
    gameCategory: 'card',
    icon: '🌟',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.ShowcaseCharacter,
      audience: AudienceType.Male2535,
    },
    preview: '【镜头1】抽卡界面 → 金光特效\n【镜头2】SSR角色破碎登场\n【镜头3】角色大招演出',
    recommendedSellTags: ['角色收集', '高级许愿'],
  },
  {
    id: 'show_shooter_combat_15',
    name: '射击战斗展示 15s',
    description: '高燃战斗场面，枪战 + 载具 + 爆炸',
    category: 'showcase',
    gameCategory: 'shooter',
    icon: '💥',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Landscape,
      scriptType: ScriptType.ShowcaseMap,
      audience: AudienceType.Male1824,
    },
    preview: '【镜头1】第一人称开镜狙杀\n【镜头2】载具追逐爆炸\n【镜头3】团队冲锋占点',
  },
  {
    id: 'show_sim_build_30',
    name: '模拟经营建造展示 30s',
    description: '从空地到豪华庄园的建造过程快速展示',
    category: 'showcase',
    gameCategory: 'sim',
    icon: '🏠',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.ShowcaseMap,
      audience: AudienceType.General,
    },
    preview: '【镜头1】一片空地 → 放置第一栋建筑\n【镜头2】加速建造 → 城镇逐渐繁华\n【镜头3】俯瞰全景 + 收益面板',
  },
  {
    id: 'show_casual_gameplay_15',
    name: '休闲玩法展示 15s',
    description: '直接展示核心玩法，不需旁白，纯画面吸引',
    category: 'showcase',
    gameCategory: 'casual',
    icon: '🧩',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.ShowcaseMap,
      audience: AudienceType.General,
    },
    preview: '【镜头1】手指操作消除/合成\n【镜头2】连锁反应 → 满屏特效\n【镜头3】关卡完成 → 奖励弹出',
    recommendedThemeIds: ['asmr', 'merge'],
  },

  // ═══════════════════════════════════════
  //  剧情类
  // ═══════════════════════════════════════
  {
    id: 'story_slg_drama_30',
    name: 'SLG 剧情反转 30s',
    description: '弱变强叙事，被欺负后逆袭称霸',
    category: 'story',
    gameCategory: 'slg',
    icon: '🎭',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.Skit,
      audience: AudienceType.Male2535,
    },
    preview: '「我的城被灭了三次…忍了半个月终于养成满级部队…今天我要把他们全推了！」',
    recommendedThemeIds: ['drama', 'ceo'],
  },
  {
    id: 'story_rpg_cg_15',
    name: 'RPG CG 动画 15s',
    description: '游戏 CG 风格动画叙事，电影级质感',
    category: 'story',
    gameCategory: 'rpg',
    icon: '🎬',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Landscape,
      scriptType: ScriptType.CgStory,
      audience: AudienceType.Male1824,
    },
    preview: '【镜头1】暗夜中勇者拔剑\n【镜头2】与魔王对峙，光暗交锋\n【镜头3】终结一击，光芒万丈',
    recommendedThemeIds: ['zombie', 'survive'],
  },
  {
    id: 'story_casual_fail_15',
    name: '休闲失败诱导 15s',
    description: '故意展示失败操作，激发"我能做得更好"的心理',
    category: 'story',
    gameCategory: 'casual',
    icon: '🤦',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.Skit,
      audience: AudienceType.General,
    },
    preview: '「这么简单都过不了？」→ 故意走错路线 → 离正确答案一步之遥 →「你来试试！」',
  },
  {
    id: 'story_acg_plot_30',
    name: '二次元剧情向 30s',
    description: '用CG和对白讲述游戏剧情，制造情感共鸣',
    category: 'story',
    gameCategory: 'acg',
    icon: '💔',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.CgStory,
      audience: AudienceType.Male1824,
    },
    preview: '【镜头1】角色在雨中回忆过去\n【镜头2】战斗中保护同伴\n【镜头3】觉醒新力量，含泪一击',
  },
  {
    id: 'story_card_summon_30',
    name: '卡牌召唤剧情 30s',
    description: '围绕抽卡/召唤的微剧情，制造期待感',
    category: 'story',
    gameCategory: 'card',
    icon: '🔮',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.Skit,
      audience: AudienceType.Male2535,
    },
    preview: '「最后一抽了…求求给个SSR…」→ 金光特效 → 传说级角色登场 →「啊啊啊！！！」',
    recommendedSellTags: ['高级许愿'],
  },
  {
    id: 'story_moba_clutch_15',
    name: 'MOBA 翻盘剧情 15s',
    description: '绝境翻盘高光时刻，制造热血感',
    category: 'story',
    gameCategory: 'moba',
    icon: '🔥',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.Skit,
      audience: AudienceType.Male1824,
    },
    preview: '「三路高地全破了…但我还没放弃！」→ 极限1v5操作 → 五杀翻盘 →「永远不要投降！」',
  },
  {
    id: 'story_shooter_mission_30',
    name: '射击任务剧情 30s',
    description: '特种行动风格叙事，紧张刺激的任务剧情',
    category: 'story',
    gameCategory: 'shooter',
    icon: '🎯',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 30,
      aspectRatio: AspectRatio.Landscape,
      scriptType: ScriptType.CgStory,
      audience: AudienceType.Male1824,
    },
    preview: '【镜头1】小队潜入敌方基地\n【镜头2】被发现，激烈枪战\n【镜头3】爆破逃离，直升机撤退',
  },
  {
    id: 'story_sim_growth_30',
    name: '模拟经营成长故事 30s',
    description: '从破产到富翁的逆袭故事',
    category: 'story',
    gameCategory: 'sim',
    icon: '📈',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.Skit,
      audience: AudienceType.General,
    },
    preview: '「负债100万开局…先开个小店…三个月后我成了全服首富！这是我的商业帝国…」',
  },

  // ═══════════════════════════════════════
  //  UE 创意
  // ═══════════════════════════════════════
  {
    id: 'ue_rpg_pv_15',
    name: 'UE RPG PV 15s',
    description: 'UE 引擎制作的 RPG 宣传 PV，电影级画质',
    category: 'ue',
    gameCategory: 'rpg',
    icon: '🎥',
    config: {
      direction: ProductionDirection.UeGameplay,
      duration: 15,
      aspectRatio: AspectRatio.Landscape,
      scriptType: ScriptType.UeShowcasePV,
      ueContentType: UeContentType.Showcase,
    },
    preview: '【镜头1】史诗级开场 → 大陆全景\n【镜头2】英雄集结 → 战斗展示\n【镜头3】LOGO + 下载引导',
  },
  {
    id: 'ue_slg_maprun_15',
    name: 'UE SLG 地图漫游 15s',
    description: '虚幻引擎 SLG 地图漫游，展示城池和战场',
    category: 'ue',
    gameCategory: 'slg',
    icon: '🌍',
    config: {
      direction: ProductionDirection.UeGameplay,
      duration: 15,
      aspectRatio: AspectRatio.Landscape,
      scriptType: ScriptType.UeShowcaseMapRun,
      ueContentType: UeContentType.Showcase,
    },
    preview: '【镜头1】从天空俯冲到城池\n【镜头2】兵种列阵行军\n【镜头3】攻城战全景',
  },
  {
    id: 'ue_acg_char_15',
    name: 'UE 二次元角色 15s',
    description: 'UE 引擎二次元角色展示，卡通渲染风格',
    category: 'ue',
    gameCategory: 'acg',
    icon: '🤖',
    config: {
      direction: ProductionDirection.UeGameplay,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.UeShowcaseCharacter,
      ueContentType: UeContentType.Showcase,
    },
    preview: '【镜头1】角色卡通渲染全身展示\n【镜头2】表情动画特写\n【镜头3】战斗动作 + 大招释放',
  },
  {
    id: 'ue_shooter_gameplay_30',
    name: 'UE 射击实机 30s',
    description: 'UE 引擎 FPS 实机画面，展示枪械手感和场景破坏',
    category: 'ue',
    gameCategory: 'shooter',
    icon: '💣',
    config: {
      direction: ProductionDirection.UeGameplay,
      duration: 30,
      aspectRatio: AspectRatio.Landscape,
      scriptType: ScriptType.UeGameplayScript,
      ueContentType: UeContentType.Gameplay,
    },
    preview: '【镜头1】第一人称换弹 → 冲锋\n【镜头2】场景破坏 → 墙壁碎裂\n【镜头3】多人对战 → 战术配合',
  },
  {
    id: 'ue_moba_gameplay_30',
    name: 'UE MOBA 实机 30s',
    description: 'UE 引擎 MOBA 团战展示，技能特效拉满',
    category: 'ue',
    gameCategory: 'moba',
    icon: '⚔️',
    config: {
      direction: ProductionDirection.UeGameplay,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.UeGameplayScript,
      ueContentType: UeContentType.Gameplay,
    },
    preview: '【镜头1】英雄选择 → 加载\n【镜头2】中路对线 → 技能拉扯\n【镜头3】大龙团战 → 五杀终结',
  },
  {
    id: 'ue_rpg_gameplay_30',
    name: 'UE RPG 副本实机 30s',
    description: 'UE 引擎 RPG 副本实机，BOSS战和掉落展示',
    category: 'ue',
    gameCategory: 'rpg',
    icon: '🐉',
    config: {
      direction: ProductionDirection.UeGameplay,
      duration: 30,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.UeGameplayScript,
      ueContentType: UeContentType.Gameplay,
    },
    preview: '【镜头1】进入副本 → 怪物出现\n【镜头2】BOSS战 → 走位躲技能\n【镜头3】BOSS倒下 → 紫色装备掉落',
  },
  {
    id: 'ue_sim_showcase_15',
    name: 'UE 模拟经营展示 15s',
    description: 'UE 引擎展示精美建筑和经营场景',
    category: 'ue',
    gameCategory: 'sim',
    icon: '🏙️',
    config: {
      direction: ProductionDirection.UeGameplay,
      duration: 15,
      aspectRatio: AspectRatio.Landscape,
      scriptType: ScriptType.UeShowcasePV,
      ueContentType: UeContentType.Showcase,
    },
    preview: '【镜头1】微缩城市鸟瞰 → 阳光洒落\n【镜头2】街道细节 → NPC活动\n【镜头3】夜景霓虹 → 整体俯瞰',
  },
  {
    id: 'ue_card_summon_15',
    name: 'UE 卡牌召唤动画 15s',
    description: 'UE 引擎制作的抽卡/召唤 3D 动画',
    category: 'ue',
    gameCategory: 'card',
    icon: '🌀',
    config: {
      direction: ProductionDirection.UeGameplay,
      duration: 15,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.UeShowcasePV,
      ueContentType: UeContentType.Showcase,
    },
    preview: '【镜头1】魔法阵旋转 → 光芒汇聚\n【镜头2】卡牌从天而降 → 破碎化为角色\n【镜头3】角色帅气亮相',
    recommendedSellTags: ['高级许愿'],
  },

  // ═══════════════════════════════════════
  //  更多热门 — 补充各品类 Hook 和跨品类模板
  // ═══════════════════════════════════════
  {
    id: 'popular_slg_hook_5',
    name: 'SLG 5秒钩子',
    description: '极短攻城画面，快速抓住策略玩家注意力',
    category: 'popular',
    gameCategory: 'slg',
    icon: '🏰',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 5,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.Hook5s,
      audience: AudienceType.Male2535,
    },
    preview: '满屏部队冲锋 → 城墙爆破 →「能打下来算我输！」',
  },
  {
    id: 'popular_rpg_hook_5',
    name: 'RPG 5秒钩子',
    description: '角色大招一击必杀，强视觉冲击',
    category: 'popular',
    gameCategory: 'rpg',
    icon: '💫',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 5,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.Hook5s,
      audience: AudienceType.Male1824,
    },
    preview: '满血BOSS → 一刀999999 → BOSS倒地 →「这伤害真实的？」',
    recommendedThemeIds: ['boss'],
  },
  {
    id: 'popular_shooter_hook_5',
    name: '射击游戏 5秒钩子',
    description: '精彩击杀瞬间，一枪制胜',
    category: 'popular',
    gameCategory: 'shooter',
    icon: '🎯',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 5,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.Hook5s,
      audience: AudienceType.Male1824,
    },
    preview: '开镜 → 远距离爆头 → 连杀提示 →「这枪法你打几分？」',
  },
  {
    id: 'popular_sim_hook_5',
    name: '模拟经营 5秒钩子',
    description: '快速展示从零到繁华的建造过程',
    category: 'popular',
    gameCategory: 'sim',
    icon: '🌆',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 5,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.Hook5s,
      audience: AudienceType.General,
    },
    preview: '空地 → 快进建造 → 华丽城市 →「3天就建成了！」',
  },
  {
    id: 'popular_card_hook_5',
    name: '卡牌 5秒钩子',
    description: '十连抽全金特效，制造欧气感',
    category: 'popular',
    gameCategory: 'card',
    icon: '🎊',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 5,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.Hook5s,
      audience: AudienceType.Male2535,
    },
    preview: '十连抽 → 全金卡 → 三个SSR →「这是什么神仙运气！」',
    recommendedSellTags: ['高级许愿'],
  },
  {
    id: 'popular_moba_hook_5',
    name: 'MOBA 5秒钩子',
    description: '五杀高光瞬间，热血操作',
    category: 'popular',
    gameCategory: 'moba',
    icon: '🔥',
    config: {
      direction: ProductionDirection.Script2D,
      duration: 5,
      aspectRatio: AspectRatio.Portrait,
      scriptType: ScriptType.Hook5s,
      audience: AudienceType.Male1824,
    },
    preview: '极限走位 → 连续击杀 → PENTAKILL →「这操作你能做到？」',
  },
]
