import type { GameplayPreset } from '@/models/types'

export const UE_GAMEPLAY_PRESETS: GameplayPreset[] = [
  // T1 爆热
  {
    id: 'mowing',
    name: '割草/幸存者',
    tier: 'T1',
    description: 'Survivor.io 式满屏清怪，视觉冲击+数值成长',
    visualHook: '满屏怪物被一次性清空的爆炸特效',
    coreLoop: '移动躲避→自动攻击→升级选技能→怪潮升级→Boss战',
    tags: ['割草', '幸存者', '弹幕', 'Roguelike'],
  },
  {
    id: 'pinball',
    name: '弹球/弹射',
    tier: 'T1',
    description: '物理碰撞+连锁反应爽感，一发入魂',
    visualHook: '弹球连续碰撞产生连锁反应的慢镜头',
    coreLoop: '瞄准发射→碰撞连锁→消除得分→解锁强化弹球',
    tags: ['弹球', '弹射', '物理', '连锁'],
  },
  {
    id: 'dragon_zuma',
    name: '打龙/祖玛',
    tier: 'T1',
    description: '管理分配+节点决策，日耗百万级验证玩法',
    visualHook: '龙珠连消引发全屏爆炸的链式反应',
    coreLoop: '发射匹配→消除链→资源分配→Boss节点决策',
    tags: ['祖玛', '打龙', '消除', '决策'],
  },
  {
    id: 'merge',
    name: '合成/合并',
    tier: 'T1',
    description: '两两合成不断进化，Merge品类增长20%+',
    visualHook: '低级单位合成瞬间变成高级华丽形态',
    coreLoop: '收集单位→两两合并→形态进化→解锁新物种',
    tags: ['合成', '合并', '进化', 'Merge'],
  },
  {
    id: 'pull_pin',
    name: '拉环解谜',
    tier: 'T1',
    description: 'Pull the Pin 式关卡，SLG 破圈利器',
    visualHook: '拉错一根环导致岩浆/怪物涌出的灾难瞬间',
    coreLoop: '观察关卡→选择拉环顺序→触发机关→通关/失败',
    tags: ['拉环', '解谜', '关卡', 'Pull Pin'],
  },
  // T2 中热
  {
    id: 'snake_io',
    name: '贪吃蛇/IO',
    tier: 'T2',
    description: '不断变大的视觉满足，多人竞技对抗',
    visualHook: '从小蛇到占满全屏的巨蟒的成长过程',
    coreLoop: '移动吞噬→体型增长→包围对手→称霸全场',
    tags: ['贪吃蛇', 'IO', '竞技', '成长'],
  },
  {
    id: 'tower_defense',
    name: '塔防',
    tier: 'T2',
    description: '排兵布阵防守关卡，策略爽感满满',
    visualHook: '密集怪潮被防御塔火力网全歼的航拍镜头',
    coreLoop: '布置防御→怪潮来袭→升级塔楼→策略调整',
    tags: ['塔防', '策略', '布阵', '防守'],
  },
  {
    id: 'match3',
    name: '消除/三消',
    tier: 'T2',
    description: '经典品类，受众极广，老少皆宜',
    visualHook: '大范围连消引发全屏华丽特效',
    coreLoop: '交换匹配→消除得分→触发特殊道具→连锁反应',
    tags: ['三消', '消除', '匹配', '休闲'],
  },
  {
    id: 'idle',
    name: '放置/挂机',
    tier: 'T2',
    description: '离线收益+数值膨胀，碎片时间友好',
    visualHook: '离线一夜后打开游戏获得海量奖励的瞬间',
    coreLoop: '挂机收益→数值膨胀→突破瓶颈→解锁新阶段',
    tags: ['放置', '挂机', '数值', '碎片'],
  },
  {
    id: 'sort',
    name: '排序/整理',
    tier: 'T2',
    description: '瓶子分类/颜色排序，解压向强吸量',
    visualHook: '杂乱液体精准分类到对应瓶子的流畅过程',
    coreLoop: '观察颜色→移动排序→逐步归位→完美通关',
    tags: ['排序', '分类', '解压', '整理'],
  },
  // T3 常青
  {
    id: 'runner',
    name: '跑酷/Runner',
    tier: 'T3',
    description: '闯关类节奏快，操作门槛低',
    visualHook: '角色在障碍中极限穿梭的流畅镜头',
    coreLoop: '奔跑→躲避障碍→收集道具→冲刺终点',
    tags: ['跑酷', '闯关', '节奏', 'Runner'],
  },
  {
    id: 'sliding_puzzle',
    name: '华容道/滑块',
    tier: 'T3',
    description: '空间推理解谜，烧脑但上瘾',
    visualHook: '最后一步滑动完成拼图的"啊哈"时刻',
    coreLoop: '分析布局→移动滑块→腾出路径→解开谜题',
    tags: ['华容道', '滑块', '解谜', '烧脑'],
  },
  {
    id: 'tycoon',
    name: '模拟经营',
    tier: 'T3',
    description: '建造+管理，从小摊到商业帝国',
    visualHook: '俯瞰视角下帝国从一间小店扩展到整个城市',
    coreLoop: '建造设施→服务客户→赚取利润→扩张升级',
    tags: ['模拟', '经营', '建造', 'Tycoon'],
  },
  {
    id: 'shooter',
    name: '射击/枪战',
    tier: 'T3',
    description: '轻度FPS/TPS，快节奏对抗',
    visualHook: '子弹时间中精准爆头的慢动作特写',
    coreLoop: '瞄准射击→击杀敌人→收集装备→推进关卡',
    tags: ['射击', '枪战', 'FPS', 'TPS'],
  },
  {
    id: 'asmr_satisfy',
    name: '解压/ASMR',
    tier: 'T3',
    description: '碾碎切割，极致感官满足',
    visualHook: '液压机碾碎物品或切割凝胶的ASMR特写',
    coreLoop: '选择物品→碾碎/切割/挤压→感官满足→解锁新工具',
    tags: ['解压', 'ASMR', '碾碎', '切割'],
  },
]
